#!/usr/bin/env python3
"""Synchronize generated worker definitions with dstack profiles."""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Mapping, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))

import configure  # noqa: E402


class BindingError(Exception):
    pass


def worker_name(profile: str) -> str:
    return "dstack-{}".format(profile)


def render(profile: str, binding: Mapping[str, str]) -> str:
    return (
        "---\n"
        "name: {name}\n"
        "description: dstack {profile} worker. Its model and effort are pinned by the "
        "{profile} profile in ~/.dstack/config.json.\n"
        "model: {model}\n"
        "effort: {effort}\n"
        "---\n"
        "\n"
        "<!-- dstack-managed-worker: {profile} -->\n"
        "\n"
        "You are the dstack `{profile}` worker. This file is generated by setup-dstack; "
        "edit the profile instead of this file.\n"
        "\n"
        "Follow the brief you are given exactly, stay inside the scope it names, and report "
        "the artifact or findings it asks for. Do not change your own model or effort.\n"
    ).format(
        name=worker_name(profile),
        profile=profile,
        model=binding["model"],
        effort=binding["effort"],
    )


def load_host_entry(host: str) -> Dict[str, Any]:
    path = configure.CONFIG_PATH
    if not path.exists():
        raise BindingError("no dstack configuration at {}; run setup-dstack".format(path))
    config = configure.validate_config(configure.read_json(path, str(path)))
    entry = config["hosts"].get(host)
    if entry is None:
        raise BindingError("host {!r} has no entry in {}; run setup-dstack".format(host, path))
    return entry


def write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=str(path.parent), prefix=".worker.", suffix=".tmp", delete=False
    ) as temporary:
        temporary_path = Path(temporary.name)
        try:
            temporary.write(text)
            temporary.flush()
            os.fsync(temporary.fileno())
        except Exception:
            temporary_path.unlink(missing_ok=True)
            raise
    try:
        os.replace(str(temporary_path), str(path))
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise


def sync(host: str) -> List[str]:
    entry = load_host_entry(host)
    if entry["worker_binding"]["mechanism"] == configure.SPAWN_ARGUMENTS:
        return [
            "host {} applies each profile as spawn arguments; no worker definitions are needed".format(host)
        ]

    directory = Path(entry["worker_binding"]["definitions_directory"])
    lines: List[str] = ["worker definitions for host {} in {}".format(host, directory)]
    for profile in configure.PROFILES:
        path = directory / "{}.md".format(worker_name(profile))
        expected = render(profile, entry["profiles"][profile])
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == expected:
            state = "unchanged"
        else:
            state = "created" if current is None else "updated"
            write_atomic(path, expected)
        if path.read_text(encoding="utf-8") != expected:
            raise BindingError("{} does not match the {} profile after synchronization".format(path, profile))
        lines.append("  {} {}".format(state, path.name))
    lines.append("all four profiles are pinned to a concrete model and effort pair")
    return lines


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description="Synchronize dstack worker definitions.")
    result.add_argument("--host", required=True)
    return result


def run(arguments: Sequence[str]) -> int:
    options = parser().parse_args(arguments)
    try:
        host = configure.validate_host(options.host, "--host")
        for line in sync(host):
            print(line)
        return 0
    except (BindingError, configure.ConfigError, OSError) as error:
        print("Worker bindings failed: {}".format(error), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(run(sys.argv[1:]))
